name: Upload data to temp-azure database on release

on:
  release:
    types: [released]

jobs:
  publish:
    uses: Geological-Survey-of-Western-Australia/Vocabularies/.github/workflows/upload-to-database.yml@main
    with:
      environment: temp-azure
      request_timeout: 300
    secrets:
      prez_url: ${{ secrets.PREZ_URL }}
      database_url: ${{ secrets.FUSEKI_DATASET_URL }}
      database_username: ${{ secrets.FUSEKI_USERNAME }}
      database_password: ${{ secrets.FUSEKI_PASSWORD }}
